-- MySQL Script generated by MySQL Workbench
-- 03/01/17 23:34:32
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estado` (
  `id_estado` INT NOT NULL,
  PRIMARY KEY (`id_estado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cidade` (
  `idcidade` INT NOT NULL,
  `descricao_cidade` VARCHAR(45) NOT NULL,
  `idestado` VARCHAR(45) NULL,
  `estado_idestado` INT NOT NULL,
  `estado_idestado1` INT NOT NULL,
  PRIMARY KEY (`idcidade`, `estado_idestado`),
  INDEX `fk_cidade_estado1_idx` (`estado_idestado1` ASC),
  CONSTRAINT `fk_cidade_estado1`
    FOREIGN KEY (`estado_idestado1`)
    REFERENCES `mydb`.`estado` (`id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_pessoa` (
  `idtipo_pessoa` INT NOT NULL,
  `tipo_pessoa_descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtipo_pessoa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pessoa` (
  `id_Pessoa` INT NOT NULL,
  `cpf_Pessoa` INT NOT NULL,
  `nome_Pessoa` VARCHAR(80) NOT NULL,
  `email_Pessoa` CHAR(1) NOT NULL,
  `telefone_Pessoa` DECIMAL(10,0) NOT NULL,
  `data_de_nascimento_Pessoa` VARCHAR(25) NOT NULL,
  `estado_Pessoa` VARCHAR(45) NOT NULL,
  `cidade_Pessoa` VARCHAR(45) NOT NULL,
  `endereco_Pessoa` VARCHAR(80) NOT NULL,
  `estado_civil_Pessoa` VARCHAR(45) NOT NULL,
  `filhos_pessoa` VARCHAR(45) NULL,
  `cidade_idcidade` INT NOT NULL,
  `cidade_estado_idestado` INT NOT NULL,
  `tipo_pessoa_idtipo_pessoa` INT NOT NULL,
  `cidade_idcidade1` INT NOT NULL,
  `cidade_estado_idestado1` INT NOT NULL,
  `tipo_pessoa_idtipo_pessoa1` INT NOT NULL,
  PRIMARY KEY (`id_Pessoa`, `cidade_estado_idestado`, `tipo_pessoa_idtipo_pessoa`, `cidade_idcidade`),
  UNIQUE INDEX `cpf_Pessoa_UNIQUE` (`id_Pessoa` ASC),
  INDEX `fk_Pessoa_cidade2_idx` (`cidade_idcidade1` ASC, `cidade_estado_idestado1` ASC),
  INDEX `fk_Pessoa_tipo_pessoa2_idx` (`tipo_pessoa_idtipo_pessoa1` ASC),
  CONSTRAINT `fk_Pessoa_cidade2`
    FOREIGN KEY (`cidade_idcidade1` , `cidade_estado_idestado1`)
    REFERENCES `mydb`.`cidade` (`idcidade` , `estado_idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pessoa_tipo_pessoa2`
    FOREIGN KEY (`tipo_pessoa_idtipo_pessoa1`)
    REFERENCES `mydb`.`tipo_pessoa` (`idtipo_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`notificacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`notificacao` (
  `id_notificacao` INT NOT NULL,
  `id_gestor` INT NULL,
  `id_administrador` INT NULL,
  `id_funcionario` INT NULL,
  `estatus_notificacao` VARCHAR(45) NOT NULL,
  `assunto_notificacao` VARCHAR(80) NOT NULL,
  `data_entrega_notificacao` DATETIME NOT NULL,
  `conteudo_notificacao` VARCHAR(200) NOT NULL,
  `Pessoa_id_Pessoa` INT NOT NULL,
  `Pessoa_cidade_idcidade` INT NOT NULL,
  `Pessoa_cidade_estado_idestado` INT NOT NULL,
  `Pessoa_tipo_pessoa_idtipo_pessoa` INT NOT NULL,
  `Pessoa_id_Pessoa1` INT NOT NULL,
  `Pessoa_cidade_idcidade1` INT NOT NULL,
  `Pessoa_cidade_estado_idestado1` INT NOT NULL,
  `Pessoa_tipo_pessoa_idtipo_pessoa1` INT NOT NULL,
  PRIMARY KEY (`id_notificacao`),
  INDEX `fk_notificacao_Pessoa1_idx` (`Pessoa_id_Pessoa` ASC, `Pessoa_cidade_idcidade` ASC, `Pessoa_cidade_estado_idestado` ASC, `Pessoa_tipo_pessoa_idtipo_pessoa` ASC),
  INDEX `fk_notificacao_Pessoa2_idx` (`Pessoa_id_Pessoa1` ASC, `Pessoa_cidade_idcidade1` ASC, `Pessoa_cidade_estado_idestado1` ASC, `Pessoa_tipo_pessoa_idtipo_pessoa1` ASC),
  CONSTRAINT `fk_notificacao_Pessoa1`
    FOREIGN KEY (`Pessoa_id_Pessoa` , `Pessoa_cidade_idcidade` , `Pessoa_cidade_estado_idestado` , `Pessoa_tipo_pessoa_idtipo_pessoa`)
    REFERENCES `mydb`.`Pessoa` (`id_Pessoa` , `cidade_idcidade` , `cidade_estado_idestado` , `tipo_pessoa_idtipo_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notificacao_Pessoa2`
    FOREIGN KEY (`Pessoa_id_Pessoa1` , `Pessoa_cidade_idcidade1` , `Pessoa_cidade_estado_idestado1` , `Pessoa_tipo_pessoa_idtipo_pessoa1`)
    REFERENCES `mydb`.`Pessoa` (`id_Pessoa` , `cidade_idcidade` , `cidade_estado_idestado` , `tipo_pessoa_idtipo_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
