-- MySQL Script generated by MySQL Workbench
-- 08/11/14 23:22:35
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sistemateste
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistemateste` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `sistemateste` ;

-- -----------------------------------------------------
-- Table `sistemateste`.`tb_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemateste`.`tb_cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `dtNascimento` DATE NOT NULL,
  `telefone` VARCHAR(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
